name: jogajunto_auth_contacts
description: Projeto base Flutter com login por telefone, acesso a contatos e convite por WhatsApp.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.1
  flutter_contact: ^0.9.3
  permission_handler: ^11.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
